#ifndef SHARED_HH
# define SHARED_HH

# define CUSTOM_SYSCALL_MALLOC     4444
# define CUSTOM_SYSCALL_REALLOC    5555
# define CUSTOM_SYSCALL_CALLOC     6666
# define CUSTOM_SYSCALL_FREE       7777

#endif /* SHARED_HH */
